apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: app
          image: fabau/hello-world-js:1.0.0
          ports:
            - containerPorts: 3000
          imagePullPolicy: Always
